name: ty-sign

services:
  app:
    image: ghcr.io/sn0wo2/nodeseek-api-signin:latest
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ty-sign
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../.data:/app/.data
    stdin_open: true
    tty: true
